DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS queries CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
    id bigInt GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(30) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(40) NOT NULL,
    CONSTRAINT unique_username UNIQUE (username)
);

CREATE TABLE queries
(
    "ownerId" bigint NOT NULL,
    id bigInt GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "jsonData" jsonb NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT fk_ownerId FOREIGN KEY ("ownerId") REFERENCES users(id)
);


CREATE TABLE profiles
(
    id bigInt GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ownerId" bigint NOT NULL,
    "firstName" character varying(30) COLLATE "default",
    "lastName" character varying(40) COLLATE "default",
    "phoneNumber" character varying(12) COLLATE "default",
    address character varying(40) COLLATE "default",
    country character varying(20) COLLATE "default",
    city character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT fk_ownerId FOREIGN KEY ("ownerId") REFERENCES users(id)
);


CREATE TABLE friends
(
    id bigInt GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id1 bigint NOT NULL,
    id2 bigint NOT NULL,
    CONSTRAINT fk_friend1 FOREIGN KEY (id1) REFERENCES users(id),
    CONSTRAINT fk_friend2 FOREIGN KEY (id2) REFERENCES users(id)
);


CREATE OR REPLACE FUNCTION default_query_name()
RETURNS TRIGGER AS $$
BEGIN
     UPDATE queries SET name = 'Default';
     RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_save_query
    AFTER INSERT ON public.queries
    FOR EACH ROW
    EXECUTE FUNCTION default_query_name();

CREATE OR REPLACE FUNCTION create_profile_on_user_insert()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO profiles ("ownerId") VALUES (NEW.id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_create_profile
    AFTER INSERT ON users
    FOR EACH ROW
    EXECUTE FUNCTION create_profile_on_user_insert();
    
INSERT INTO users (username, password, email) VALUES
('user0', '$2y$10$Gsz/wuCLPils8spwHV1PCOD8zupap7q.fkTwJC5v.xRqX1FYCMYlu', 'user0@mail.com'),
('user1', '$2y$10$D2tfPkiZ/P34CgQm64C1..1o16AykKMag5sVQn0k2fr4CDJe/TJgW', 'user1@mail.com'),
('user2', '$2y$10$o.7I8yvJ7o59uQEhvaJQjuxDzdd5V6b8QvujB1KeSskes/jiU4VIu', 'user2@mail.com'),
('user3', '$2y$10$x0orKrJk7aNln/Lfhx61feRhVmbqv1a7U5y95U/Dw463hhFudFtem', 'user3@mail.com'),
('user4', '$2y$10$I9ScYhT73HZrAFOhEfgjlON9JqZKZWw6TVxZIoXZcyIrc5mjrJDYO', 'user4@mail.com'),
('user5', '$2y$10$yH3uy/iWKhdK0XXN3pufLOfxs6P45Biy42LFRVJJhDIFmMogs1e4m', 'user5@mail.com'),
('user6', '$2y$10$9dD/K3XwY5Cas63XPSNDmujQXNsF8CkR0E1tg5AP58TNyKUyHntPy', 'user6@mail.com'),
('user7', '$2y$10$RYW55tR9ZxjFmBuIK0IzWe1TDE/xviJPGcTzzyjABOlhMqeG.EqdC', 'user7@mail.com'),
('user8', '$2y$10$Nm5MPP/hzTcz.Tg24QmnauqIXaIqWyQSHN4QJQFsbDIWiqrvA8QiK', 'user8@mail.com'),
('user9', '$2y$10$W36mXziEf669qjEEYX0b8ey7zkxH5qACbjAWluMpkAkpC5IgRKCE.', 'user9@mail.com'),
('user10', '$2y$10$DRHCt.rpeQkF3GcHgr880efuqDhfaWbb3/714E6p1U.Ogs21PK20y', 'user10@mail.com'),
('user11', '$2y$10$.48cpbkxPnowjRcYEgnyoephE3bx/jrAkaLXG.c2N80CcxpEUR0A.', 'user11@mail.com'),
('user12', '$2y$10$onWKpjKr7nJcUNxF.3QiIe3Ek9grvmSO.mLN4VGOxz.Kn/yO4a8lS', 'user12@mail.com'),
('user13', '$2y$10$F1ipfoxGvzyPl1k7G6EOvOUR4HchnQK.dDO/2IHfhUDMYSwdLYM3q', 'user13@mail.com'),
('user14', '$2y$10$cR8k4y.7FKJGgrginALneu52Z9sagO.bmGIfqr9FWjbQDMreDImIy', 'user14@mail.com'),
('user15', '$2y$10$oOZN1tSCoO8g2wqHw5dJBuxqWfmp8lURjnvGvz9Nf3eqCLPjKZy1q', 'user15@mail.com'),
('user16', '$2y$10$vUTcQ0.Z6GfCzDj4NgvXF.nyaoZkg/fjoOdA5GcEBxpAo.pA1sLwC', 'user16@mail.com'),
('user17', '$2y$10$l213lE8ZECj/Rsh3C9kLqe.LE6R4bHfhLl9F7qn5BwmBnW9A.uktW', 'user17@mail.com'),
('user18', '$2y$10$VqYWjvp52G4RrpoXWa4CI.0ys8cgEqFkYSSUdMCGz8XmMgylg.g56', 'user18@mail.com'),
('user19', '$2y$10$y3.8xFrfvWMmw6tcbd90xOaqlX7BScxqzJlB3v08Z20crQGQZwFoa', 'user19@mail.com'),
('user20', '$2y$10$retvpd8C.b2Es2n/CXNx9eMySLR8y2xF4Le4.ICeAe59QMLGEIthO', 'user20@mail.com'),
('user21', '$2y$10$g0fX4K2F.93w6ImzzCMwgO6YbKCSJs21AwGIylhB9dJCep3YL429m', 'user21@mail.com'),
('user22', '$2y$10$bBVpzrA/EZfoJJxZysrLWuWymyhsRnQUsEOhBeokkJM4.2ZEd0aK.', 'user22@mail.com'),
('user23', '$2y$10$kGc3wG9xEOFaexNxoehAJu8Cdah4w7jDuylNmR824xhEAxy3eWJBS', 'user23@mail.com'),
('user24', '$2y$10$Qi1PTSFBcLn8Aqz8qnrmYOpYsYCaV6dKY8wi9XVLqrSf2T2QdDubq', 'user24@mail.com'),
('user25', '$2y$10$wC5S53DJexaIGGZpuPGPoeQevkGKn4gh/XlDtU0kp91/wWIlDFViu', 'user25@mail.com'),
('user26', '$2y$10$QwdC3J2/LX.UGRW7hP4KHO8jBIrJa0qaHnlvY/Chol3V0bkMq.WXO', 'user26@mail.com'),
('user27', '$2y$10$cg0Vep4TdkRl2PmgVmyRVuIj2dfI9Y.NOcNkhxvmgL/0DQkAn3N..', 'user27@mail.com'),
('user28', '$2y$10$SSefBH7WCdg6hqb1bfA0yO9jiQmtRn2ybS1ieWu132c7FoBUKeHwm', 'user28@mail.com'),
('user29', '$2y$10$DGO1NvObZW5wiLkNYi6nbeQUS2NVXhz3jIsX.NbHZrWdsPf5acFcO', 'user29@mail.com'),
('user30', '$2y$10$hegYgt2FhxzhqLpN3mIBd.6DBryIq15AnRiaRdIncCcs4ENGWRmAq', 'user30@mail.com'),
('user31', '$2y$10$fm5nGWJNItkk3Pw9qHbCvu3ZTkYBKCbn5KElyPvDMm9ts2rzSWPAW', 'user31@mail.com'),
('user32', '$2y$10$U/TWPBlcT.DXzliq6jiRaukTCPvSdqxnWmnmRTaiJHYXIjLVeELXC', 'user32@mail.com'),
('user33', '$2y$10$TJaApFioKZskxMdt/9.SR.i0eTah9uQnC7LIo6/e2VcsrFdEuFHl.', 'user33@mail.com'),
('user34', '$2y$10$2ET8mboAD1cXexlU5nxsS.VNZGYZvCbmfT9BQXJzrb2MzoT8RUXmm', 'user34@mail.com'),
('user35', '$2y$10$xQTS02Ztq1wr3cECDxTBZeR74/aTz5XLqofs1U3tvccDi6SDwGGxe', 'user35@mail.com'),
('user36', '$2y$10$7h5pUlyHFRLUUg4serfgmetySACeHEPiRR1M6MsONQhYzNIcq9scS', 'user36@mail.com'),
('user37', '$2y$10$ITVA1f4GMpNVSHCszHOLj.CsqWQ6H.RVuIjuEVjdpIjMseDGtbzXe', 'user37@mail.com'),
('user38', '$2y$10$jDnTVro8MM9BviQXi9XL5e7KGkiGiUu/Bk8IOKefW6MwgqWypnMAW', 'user38@mail.com'),
('user39', '$2y$10$Wv9EI4eemv77DfCzcO8Yq.KQgmzD1jYAWo3I5vuQjWEZQ3v8cpSC6', 'user39@mail.com'),
('user40', '$2y$10$5PlWjVaHBNwYkdNAj9Jap.0vTVkEjaRJ6ie8tvEXk5oX/i67XLqqO', 'user40@mail.com'),
('user41', '$2y$10$aIvbnN9FPGmbfd/Mu0w9MOF1oHOzPqLdCkvYiTLu8uXIOQkZj3An2', 'user41@mail.com'),
('user42', '$2y$10$F0i2zONkDlX5iupNBCDjfesQeuftoBTANKSQh4wCNpkoaSub5n5Bq', 'user42@mail.com'),
('user43', '$2y$10$vT.b0diLTzrBOs3l.bjM3eCm8UuHsZzlBrLNiPTQrr4QpUGGFyC8u', 'user43@mail.com'),
('user44', '$2y$10$I4aFvNgeJtOj91J67hgm9uhBi59ZYApUEQeBAUNABWLIo3C/pJlU.', 'user44@mail.com'),
('user45', '$2y$10$/avZraHflNtVrUIk8JyNd.u22EbN5IUmQNLLGXmbCZXSL96v2QhOu', 'user45@mail.com'),
('user46', '$2y$10$D5/VPr0JPLeAAo7ywUIutOCZ63SgDBjr20PWX5ylIDhiATMg2jp2q', 'user46@mail.com'),
('user47', '$2y$10$C6Mn1NF9Wd1Uuty55pF0Muba6Le8oXiejMwaan3fUFlSUJNmgtzUG', 'user47@mail.com'),
('user48', '$2y$10$mf6VU/y5bHN1CV9.DF/.meOTHasvRHj6FrJPxz6w.82Yj86TgC292', 'user48@mail.com'),
('user49', '$2y$10$o4qBF.gLEd6VfYU8cx7WReX20bis46fEa8i4CV1ICxLBXjlg.1Srm', 'user49@mail.com'),
('user50', '$2y$10$3/uID678DIxveokV7Hv6ieUP/4uRp.aJXApwXyZCDJTOR3qR1VhzO', 'user50@mail.com'),
('user51', '$2y$10$vdQtohK13PyFKJckMKrifumloKOAbSSRoWE7Df1N.nBba9IIFt4g2', 'user51@mail.com'),
('user52', '$2y$10$xtnVRR.wuXNrOY5xIjW8cuVkx40QujijQz6koSmyQlXxoeY38zY3a', 'user52@mail.com'),
('user53', '$2y$10$aIyvhTpXEu9U0XiFTZISEudLTlRbQvIz9bmtU7YMFWmmiFXxLuN6G', 'user53@mail.com'),
('user54', '$2y$10$CV57FFDhieounZUX.Bt9Ce6302qQAOClaSRIYv6E82SluZPl/MHdi', 'user54@mail.com'),
('user55', '$2y$10$Tzy.8Cc0C..A8cDZ52P/R.Q9zGrjBco8rrknN3mudjMS/p0Abl5jG', 'user55@mail.com'),
('user56', '$2y$10$CiWsumswA83G/RF7hrl49ejYPyr3BzVHgV6j3nySvP1Sl6R9vgBOS', 'user56@mail.com'),
('user57', '$2y$10$AlI64ALgnNiw9xynWxcEr.06pxY0.L7iSP9SKYOKWBI8VsrON0ihO', 'user57@mail.com'),
('user58', '$2y$10$yE4BG9cjfkQnkxDCDiJy/uozprPmWRtK1hdfRJZsKvGPXj4Po55mK', 'user58@mail.com'),
('user59', '$2y$10$wWb0Ns0J2Q6d7vnSyr6.S.p71lML1lcjjqDLeisDVl0dANJ1je1s2', 'user59@mail.com'),
('user60', '$2y$10$LzX95D2e.Az6dYGljSO2OeTlIncXL3cznopvfe8i3C8X3eaahyU7O', 'user60@mail.com'),
('user61', '$2y$10$KBa5qxslsjW4vkugT9AIeOkF7oLYrTi47XLnluVnucZ4Oc1eMBc7u', 'user61@mail.com'),
('user62', '$2y$10$gqlFMVMZJJF5H2cui0F/pOCCARW.rlABTrW7b4OBcs5FnR6Uyyjty', 'user62@mail.com'),
('user63', '$2y$10$keZsS2UWgbEsaYq6sN6Lu..788HEXBFwNET1mxs2bkowHanmM990G', 'user63@mail.com'),
('user64', '$2y$10$E4r/49Sla1lWk7Z.pwjtAen5hL02.jkLQrG26.eIb/NlNsiTxqyw6', 'user64@mail.com'),
('user65', '$2y$10$AkKOZ1e5zKViGIz5kMatGO4k2DC1J9KlIS.i.ULxSvcyaxOc/BV0y', 'user65@mail.com'),
('user66', '$2y$10$agUDZmCWROaS56yiwM8beuq7NnsZNQQ.WGOVJJet4hBkMI2i3oEf.', 'user66@mail.com'),
('user67', '$2y$10$iuZixeeOPO1TTv2nyf7DtO/dYR1sFhQjDpiQBcpx2.IaXwqp2PwBa', 'user67@mail.com'),
('user68', '$2y$10$2rDo64KvAPlrU.LglX2BAes90wvrbQEEQ5z2ghyg80QgqDV9TO47C', 'user68@mail.com'),
('user69', '$2y$10$jO48XkQX.6n.TJ57NEA57uA3L8/5i2q1NdVZGOlcEDcWCiEj3qkh2', 'user69@mail.com'),
('user70', '$2y$10$JYKIRPf40Q5OWE7akGFdt.ein/hf/gaK06rWB8Bt2ocNacZhsZ2TC', 'user70@mail.com'),
('user71', '$2y$10$yOGjmj5h0WFac6vGWdSiYun86SzqWBCHDvSYnMqhGxwByJLB7Rn.a', 'user71@mail.com'),
('user72', '$2y$10$V/F0Yz84qSylRqswYIbBnuuhFC89snpcJG84q2Itiupg5niul9dam', 'user72@mail.com'),
('user73', '$2y$10$wjQMgE9R4gOQEm0H0Bm5guegMo5D.f.sfylAcJelQZ70HbvNuN/Ri', 'user73@mail.com'),
('user74', '$2y$10$.YP0IU02AjWaH7VPEnoeOOgV/NCHJzf37qV12Ce4FXWEkJXw7P3H6', 'user74@mail.com'),
('user75', '$2y$10$3cPO8aJhD63AyQkEcr4SxexiXLJUGt/hMhluBJieNOPpDNBCZiQJW', 'user75@mail.com'),
('user76', '$2y$10$.WMTqZutSA81sPNDgakkf.BrONvnrvVVuqmqn2H.uL5t3mm0NpLh.', 'user76@mail.com'),
('user77', '$2y$10$RhCr/Qq0wA..zIqSL0yp2u20gvZJTlDwd0.8EVW0k7Tk3MEtjPfN2', 'user77@mail.com'),
('user78', '$2y$10$jhPKi9kmOzrF4KreaIKr2uSacsZOxKmjVgYOixdpaVMAhwQMViYg2', 'user78@mail.com'),
('user79', '$2y$10$oucRAeWAvBF6bx1t3JdmYeRWetEjCbF4Y16sdNJ2MKkZ4e.EbCJjC', 'user79@mail.com'),
('user80', '$2y$10$OXcZte0gAz68VaICBCnJNOslLlvcyUVLyBZE6V24TxE/ftiImvM3G', 'user80@mail.com'),
('user81', '$2y$10$2m0jcQp0JFG5Oy6Dx0vtnellJoQ5eLeMCz05TKdGPjWKmOqJ8Y2Xi', 'user81@mail.com'),
('user82', '$2y$10$Q2DaIsJsAGh8pN98bC.6DOKwVTc4AZMMXlFsUt1Mhn/XM42rMvaDC', 'user82@mail.com'),
('user83', '$2y$10$cyhxtsruET18AisruDZxle68oL/P2GkExa0SNpzx1HrM4P.XpaR56', 'user83@mail.com'),
('user84', '$2y$10$Ndqod0jcGaqUItOSG.AfoeTkxNFVANK222oproXnFWfL6EAY/efuO', 'user84@mail.com'),
('user85', '$2y$10$3VzAMnCjQgdvQUZaU1en.eVA8ou9J5Ta1sLRh7jnA6Btr90fuImQ2', 'user85@mail.com'),
('user86', '$2y$10$z6nWFtMRu.0Wb6jpw0raeeFkMsT/lxgqi1fLCAOUwNnbuJTOrQKXy', 'user86@mail.com'),
('user87', '$2y$10$lubwXgwMnw0VoEP97IkkduGQ5G1PwDfddyLR7T8s82IhBBS6vSuBi', 'user87@mail.com'),
('user88', '$2y$10$xKz2XuliP5Lb85AgvyGbFucQ0VtlEqN8xzSl7/bdjmNcSVHGPNA0W', 'user88@mail.com'),
('user89', '$2y$10$J/9NacZrC/kbmSktFlgXTORnONU5aoe9mszcizl98xt1hBzQy4YL6', 'user89@mail.com'),
('user90', '$2y$10$Y1afGc5qlJZNCEmIS4UBcOhLPszwwpPM7AWIb9KoZSknlD68f2Xe6', 'user90@mail.com'),
('user91', '$2y$10$mupLnRVT0eNAqaeb28MbVOx1xvvYBTfmiqDbqlGw3futyeftbbh02', 'user91@mail.com'),
('user92', '$2y$10$CIsKXU9x5jtVfH62eDUxn.ISbJgk4qsZEP1zaiQBeiw4KKhmwUL2G', 'user92@mail.com'),
('user93', '$2y$10$j2hJ/5xKEp1OXx2g4NAtT.54pwhZK9I/acFpTd1cZjtOeesZE.lca', 'user93@mail.com'),
('user94', '$2y$10$4K5zWLhzDgaD3hrS46o6vemba0/GczogX0rL1W/DyEq0.ZBh/8hcS', 'user94@mail.com'),
('user95', '$2y$10$17p1wJGFtQcIs0bybzIhK.IAmr2qnLpwh2CnoH7s6QRw1RDxhGHKe', 'user95@mail.com'),
('user96', '$2y$10$vg9se4W87uoaPrdZ.uYLOOZ5E4oOjKDn5h6stNvxARjcxYKRqSZkq', 'user96@mail.com'),
('user97', '$2y$10$G3QkeS8K3cqzSItDQjmBTuoaZQYWnt0Nl1Ko2rVHS6hxiXl535gLW', 'user97@mail.com'),
('user98', '$2y$10$4bZM8sSR.GSSDIcFVjm3jOrAXTcr4e0ZUg155JLTZLMXvsAOjMIyy', 'user98@mail.com'),
('user99', '$2y$10$iwPmn9FeUh8Mi4sjbKwRtOfZqzsNYfsmJWE9AjHpmYb6VpdWi5Z7O', 'user99@mail.com');

UPDATE profiles SET "firstName" = 'Alice', "lastName" = 'Popescu', "phoneNumber" = '0700000001', address = 'Str. Lalelelor 1', country = 'Romania', city = 'Bucharest' WHERE "ownerId" = 1;
UPDATE profiles SET "firstName" = 'Bob', "lastName" = 'Ionescu', "phoneNumber" = '0700000002', address = 'Str. Lalelelor 2', country = 'Romania', city = 'Cluj' WHERE "ownerId" = 2;
UPDATE profiles SET "firstName" = 'Carol', "lastName" = 'Georgescu', "phoneNumber" = '0700000003', address = 'Str. Lalelelor 3', country = 'Romania', city = 'Timisoara' WHERE "ownerId" = 3;
UPDATE profiles SET "firstName" = 'Dan', "lastName" = 'Dumitrescu', "phoneNumber" = '0700000004', address = 'Str. Lalelelor 4', country = 'Romania', city = 'Brasov' WHERE "ownerId" = 4;
UPDATE profiles SET "firstName" = 'Eva', "lastName" = 'Enache', "phoneNumber" = '0700000005', address = 'Str. Lalelelor 5', country = 'Romania', city = 'Constanta' WHERE "ownerId" = 5;
UPDATE profiles SET "firstName" = 'Felix', "lastName" = 'Marin', "phoneNumber" = '0700000006', address = 'Str. Lalelelor 6', country = 'Romania', city = 'Iasi' WHERE "ownerId" = 6;
UPDATE profiles SET "firstName" = 'Gina', "lastName" = 'Dobre', "phoneNumber" = '0700000007', address = 'Str. Lalelelor 7', country = 'Romania', city = 'Arad' WHERE "ownerId" = 7;
UPDATE profiles SET "firstName" = 'Horia', "lastName" = 'Barbu', "phoneNumber" = '0700000008', address = 'Str. Lalelelor 8', country = 'Romania', city = 'Oradea' WHERE "ownerId" = 8;
UPDATE profiles SET "firstName" = 'Irina', "lastName" = 'Moldovan', "phoneNumber" = '0700000009', address = 'Str. Lalelelor 9', country = 'Romania', city = 'Sibiu' WHERE "ownerId" = 9;
UPDATE profiles SET "firstName" = 'Jan', "lastName" = 'Stanciu', "phoneNumber" = '0700000010', address = 'Str. Lalelelor 10', country = 'Romania', city = 'Pitesti' WHERE "ownerId" = 10;
UPDATE profiles SET "firstName" = 'Katia', "lastName" = 'Petrescu', "phoneNumber" = '0700000011', address = 'Str. Lalelelor 11', country = 'Romania', city = 'Buzau' WHERE "ownerId" = 11;
UPDATE profiles SET "firstName" = 'Leo', "lastName" = 'Toma', "phoneNumber" = '0700000012', address = 'Str. Lalelelor 12', country = 'Romania', city = 'Galati' WHERE "ownerId" = 12;
UPDATE profiles SET "firstName" = 'Mara', "lastName" = 'Nistor', "phoneNumber" = '0700000013', address = 'Str. Lalelelor 13', country = 'Romania', city = 'Bacau' WHERE "ownerId" = 13;
UPDATE profiles SET "firstName" = 'Nelu', "lastName" = 'Vasilescu', "phoneNumber" = '0700000014', address = 'Str. Lalelelor 14', country = 'Romania', city = 'Ramnicu Valcea' WHERE "ownerId" = 14;
UPDATE profiles SET "firstName" = 'Oana', "lastName" = 'Costache', "phoneNumber" = '0700000015', address = 'Str. Lalelelor 15', country = 'Romania', city = 'Baia Mare' WHERE "ownerId" = 15;
UPDATE profiles SET "firstName" = 'Paul', "lastName" = 'Anghel', "phoneNumber" = '0700000016', address = 'Str. Lalelelor 16', country = 'Romania', city = 'Craiova' WHERE "ownerId" = 16;
UPDATE profiles SET "firstName" = 'Roxana', "lastName" = 'Calin', "phoneNumber" = '0700000017', address = 'Str. Lalelelor 17', country = 'Romania', city = 'Ploiesti' WHERE "ownerId" = 17;
UPDATE profiles SET "firstName" = 'Sorin', "lastName" = 'Ilie', "phoneNumber" = '0700000018', address = 'Str. Lalelelor 18', country = 'Romania', city = 'Satu Mare' WHERE "ownerId" = 18;
UPDATE profiles SET "firstName" = 'Teodora', "lastName" = 'Parvu', "phoneNumber" = '0700000019', address = 'Str. Lalelelor 19', country = 'Romania', city = 'Targu Mures' WHERE "ownerId" = 19;
UPDATE profiles SET "firstName" = 'Vlad', "lastName" = 'Mitrea', "phoneNumber" = '0700000020', address = 'Str. Lalelelor 20', country = 'Romania', city = 'Focsani' WHERE "ownerId" = 20;
UPDATE profiles SET "firstName" = 'Adela', "lastName" = 'Radu', "phoneNumber" = '0700000021', address = 'Str. Lalelelor 21', country = 'Romania', city = 'Botosani' WHERE "ownerId" = 21;
UPDATE profiles SET "firstName" = 'Bogdan', "lastName" = 'Voinea', "phoneNumber" = '0700000022', address = 'Str. Lalelelor 22', country = 'Romania', city = 'Piatra Neamt' WHERE "ownerId" = 22;
UPDATE profiles SET "firstName" = 'Camelia', "lastName" = 'Moraru', "phoneNumber" = '0700000023', address = 'Str. Lalelelor 23', country = 'Romania', city = 'Resita' WHERE "ownerId" = 23;
UPDATE profiles SET "firstName" = 'Darius', "lastName" = 'Popa', "phoneNumber" = '0700000024', address = 'Str. Lalelelor 24', country = 'Romania', city = 'Tulcea' WHERE "ownerId" = 24;
UPDATE profiles SET "firstName" = 'Elena', "lastName" = 'Stan', "phoneNumber" = '0700000025', address = 'Str. Lalelelor 25', country = 'Romania', city = 'Giurgiu' WHERE "ownerId" = 25;
UPDATE profiles SET "firstName" = 'Fabian', "lastName" = 'Tudor', "phoneNumber" = '0700000026', address = 'Str. Lalelelor 26', country = 'Romania', city = 'Slatina' WHERE "ownerId" = 26;
UPDATE profiles SET "firstName" = 'Gabriela', "lastName" = 'Nicolae', "phoneNumber" = '0700000027', address = 'Str. Lalelelor 27', country = 'Romania', city = 'Vaslui' WHERE "ownerId" = 27;
UPDATE profiles SET "firstName" = 'Horia', "lastName" = 'Grigore', "phoneNumber" = '0700000028', address = 'Str. Lalelelor 28', country = 'Romania', city = 'Alexandria' WHERE "ownerId" = 28;
UPDATE profiles SET "firstName" = 'Ioana', "lastName" = 'Cojocaru', "phoneNumber" = '0700000029', address = 'Str. Lalelelor 29', country = 'Romania', city = 'Calarasi' WHERE "ownerId" = 29;
UPDATE profiles SET "firstName" = 'Jeni', "lastName" = 'Radulescu', "phoneNumber" = '0700000030', address = 'Str. Lalelelor 30', country = 'Romania', city = 'Slobozia' WHERE "ownerId" = 30;
UPDATE profiles SET "firstName" = 'Klaus', "lastName" = 'Boldor', "phoneNumber" = '0700000031', address = 'Str. Lalelelor 31', country = 'Romania', city = 'Zalau' WHERE "ownerId" = 31;
UPDATE profiles SET "firstName" = 'Lavinia', "lastName" = 'Florin', "phoneNumber" = '0700000032', address = 'Str. Lalelelor 32', country = 'Romania', city = 'Targoviste' WHERE "ownerId" = 32;
UPDATE profiles SET "firstName" = 'Mihai', "lastName" = 'Gheorghe', "phoneNumber" = '0700000033', address = 'Str. Lalelelor 33', country = 'Romania', city = 'Deva' WHERE "ownerId" = 33;
UPDATE profiles SET "firstName" = 'Nicoleta', "lastName" = 'Ciobanu', "phoneNumber" = '0700000034', address = 'Str. Lalelelor 34', country = 'Romania', city = 'Sfantu Gheorghe' WHERE "ownerId" = 34;
UPDATE profiles SET "firstName" = 'Ovidiu', "lastName" = 'Neagu', "phoneNumber" = '0700000035', address = 'Str. Lalelelor 35', country = 'Romania', city = 'Miercurea Ciuc' WHERE "ownerId" = 35;
UPDATE profiles SET "firstName" = 'Paula', "lastName" = 'Baciu', "phoneNumber" = '0700000036', address = 'Str. Lalelelor 36', country = 'Romania', city = 'Bistrita' WHERE "ownerId" = 36;
UPDATE profiles SET "firstName" = 'Radu', "lastName" = 'Cristescu', "phoneNumber" = '0700000037', address = 'Str. Lalelelor 37', country = 'Romania', city = 'Vatra Dornei' WHERE "ownerId" = 37;
UPDATE profiles SET "firstName" = 'Silvia', "lastName" = 'Gabor', "phoneNumber" = '0700000038', address = 'Str. Lalelelor 38', country = 'Romania', city = 'Roman' WHERE "ownerId" = 38;
UPDATE profiles SET "firstName" = 'Tudor', "lastName" = 'Munteanu', "phoneNumber" = '0700000039', address = 'Str. Lalelelor 39', country = 'Romania', city = 'Campina' WHERE "ownerId" = 39;
UPDATE profiles SET "firstName" = 'Violeta', "lastName" = 'Stroe', "phoneNumber" = '0700000040', address = 'Str. Lalelelor 40', country = 'Romania', city = 'Medias' WHERE "ownerId" = 40;
UPDATE profiles SET "firstName" = 'Andrei', "lastName" = 'Sava', "phoneNumber" = '0700000041', address = 'Str. Lalelelor 41', country = 'Romania', city = 'Mangalia' WHERE "ownerId" = 41;
UPDATE profiles SET "firstName" = 'Bianca', "lastName" = 'Lazar', "phoneNumber" = '0700000042', address = 'Str. Lalelelor 42', country = 'Romania', city = 'Sighisoara' WHERE "ownerId" = 42;
UPDATE profiles SET "firstName" = 'Cristian', "lastName" = 'Danciu', "phoneNumber" = '0700000043', address = 'Str. Lalelelor 43', country = 'Romania', city = 'Husi' WHERE "ownerId" = 43;
UPDATE profiles SET "firstName" = 'Denisa', "lastName" = 'Voicu', "phoneNumber" = '0700000044', address = 'Str. Lalelelor 44', country = 'Romania', city = 'Curtea de Arges' WHERE "ownerId" = 44;
UPDATE profiles SET "firstName" = 'Emil', "lastName" = 'Dima', "phoneNumber" = '0700000045', address = 'Str. Lalelelor 45', country = 'Romania', city = 'Sacele' WHERE "ownerId" = 45;
UPDATE profiles SET "firstName" = 'Florina', "lastName" = 'Rus', "phoneNumber" = '0700000046', address = 'Str. Lalelelor 46', country = 'Romania', city = 'Campulung' WHERE "ownerId" = 46;
UPDATE profiles SET "firstName" = 'George', "lastName" = 'Mihalache', "phoneNumber" = '0700000047', address = 'Str. Lalelelor 47', country = 'Romania', city = 'Caracal' WHERE "ownerId" = 47;
UPDATE profiles SET "firstName" = 'Hanna', "lastName" = 'Jianu', "phoneNumber" = '0700000048', address = 'Str. Lalelelor 48', country = 'Romania', city = 'Rosiorii de Vede' WHERE "ownerId" = 48;
UPDATE profiles SET "firstName" = 'Ionut', "lastName" = 'Bejan', "phoneNumber" = '0700000049', address = 'Str. Lalelelor 49', country = 'Romania', city = 'Fagaras' WHERE "ownerId" = 49;
UPDATE profiles SET "firstName" = 'Julia', "lastName" = 'Stanescu', "phoneNumber" = '0700000050', address = 'Str. Lalelelor 50', country = 'Romania', city = 'Lugoj' WHERE "ownerId" = 50;
UPDATE profiles SET "firstName" = 'Kevin', "lastName" = 'Bacinschi', "phoneNumber" = '0700000051', address = 'Str. Lalelelor 51', country = 'Romania', city = 'Motru' WHERE "ownerId" = 51;
UPDATE profiles SET "firstName" = 'Larisa', "lastName" = 'Chirila', "phoneNumber" = '0700000052', address = 'Str. Lalelelor 52', country = 'Romania', city = 'Carei' WHERE "ownerId" = 52;
UPDATE profiles SET "firstName" = 'Marius', "lastName" = 'Nita', "phoneNumber" = '0700000053', address = 'Str. Lalelelor 53', country = 'Romania', city = 'Toplita' WHERE "ownerId" = 53;
UPDATE profiles SET "firstName" = 'Natalia', "lastName" = 'Georgian', "phoneNumber" = '0700000054', address = 'Str. Lalelelor 54', country = 'Romania', city = 'Tandarei' WHERE "ownerId" = 54;
UPDATE profiles SET "firstName" = 'Otilia', "lastName" = 'Catana', "phoneNumber" = '0700000055', address = 'Str. Lalelelor 55', country = 'Romania', city = 'Campia Turzii' WHERE "ownerId" = 55;
UPDATE profiles SET "firstName" = 'Petru', "lastName" = 'Sasu', "phoneNumber" = '0700000056', address = 'Str. Lalelelor 56', country = 'Romania', city = 'Odobesti' WHERE "ownerId" = 56;
UPDATE profiles SET "firstName" = 'Raluca', "lastName" = 'Manea', "phoneNumber" = '0700000057', address = 'Str. Lalelelor 57', country = 'Romania', city = 'Suceava' WHERE "ownerId" = 57;
UPDATE profiles SET "firstName" = 'Sebastian', "lastName" = 'Ciuta', "phoneNumber" = '0700000058', address = 'Str. Lalelelor 58', country = 'Romania', city = 'Turda' WHERE "ownerId" = 58;
UPDATE profiles SET "firstName" = 'Tania', "lastName" = 'Negoita', "phoneNumber" = '0700000059', address = 'Str. Lalelelor 59', country = 'Romania', city = 'Radauti' WHERE "ownerId" = 59;
UPDATE profiles SET "firstName" = 'Valentin', "lastName" = 'Stancu', "phoneNumber" = '0700000060', address = 'Str. Lalelelor 60', country = 'Romania', city = 'Tecuci' WHERE "ownerId" = 60;
UPDATE profiles SET "firstName" = 'Alexandra', "lastName" = 'Cernat', "phoneNumber" = '0700000061', address = 'Str. Lalelelor 61', country = 'Romania', city = 'Otopeni' WHERE "ownerId" = 61;
UPDATE profiles SET "firstName" = 'Bruno', "lastName" = 'Cazan', "phoneNumber" = '0700000062', address = 'Str. Lalelelor 62', country = 'Romania', city = 'Buftea' WHERE "ownerId" = 62;
UPDATE profiles SET "firstName" = 'Cezar', "lastName" = 'Timofte', "phoneNumber" = '0700000063', address = 'Str. Lalelelor 63', country = 'Romania', city = 'Voluntari' WHERE "ownerId" = 63;
UPDATE profiles SET "firstName" = 'Diana', "lastName" = 'Chivu', "phoneNumber" = '0700000064', address = 'Str. Lalelelor 64', country = 'Romania', city = 'Popesti-Leordeni' WHERE "ownerId" = 64;
UPDATE profiles SET "firstName" = 'Emanuel', "lastName" = 'Dascalescu', "phoneNumber" = '0700000065', address = 'Str. Lalelelor 65', country = 'Romania', city = 'Pantelimon' WHERE "ownerId" = 65;
UPDATE profiles SET "firstName" = 'Felicia', "lastName" = 'Oprea', "phoneNumber" = '0700000066', address = 'Str. Lalelelor 66', country = 'Romania', city = 'Chitila' WHERE "ownerId" = 66;
UPDATE profiles SET "firstName" = 'Gheorghe', "lastName" = 'Sima', "phoneNumber" = '0700000067', address = 'Str. Lalelelor 67', country = 'Romania', city = 'Stefanestii de Jos' WHERE "ownerId" = 67;
UPDATE profiles SET "firstName" = 'Hermina', "lastName" = 'Tudose', "phoneNumber" = '0700000068', address = 'Str. Lalelelor 68', country = 'Romania', city = 'Magurele' WHERE "ownerId" = 68;
UPDATE profiles SET "firstName" = 'Ilinca', "lastName" = 'Dumitru', "phoneNumber" = '0700000069', address = 'Str. Lalelelor 69', country = 'Romania', city = 'Bragadiru' WHERE "ownerId" = 69;
UPDATE profiles SET "firstName" = 'Jon', "lastName" = 'Lungu', "phoneNumber" = '0700000070', address = 'Str. Lalelelor 70', country = 'Romania', city = 'Domnesti' WHERE "ownerId" = 70;
UPDATE profiles SET "firstName" = 'Karina', "lastName" = 'Costin', "phoneNumber" = '0700000071', address = 'Str. Lalelelor 71', country = 'Romania', city = 'Cornetu' WHERE "ownerId" = 71;
UPDATE profiles SET "firstName" = 'Luca', "lastName" = 'Moldoveanu', "phoneNumber" = '0700000072', address = 'Str. Lalelelor 72', country = 'Romania', city = 'Clinceni' WHERE "ownerId" = 72;
UPDATE profiles SET "firstName" = 'Madalina', "lastName" = 'Fodoreanu', "phoneNumber" = '0700000073', address = 'Str. Lalelelor 73', country = 'Romania', city = 'Berceni' WHERE "ownerId" = 73;
UPDATE profiles SET "firstName" = 'Narcis', "lastName" = 'Mocanu', "phoneNumber" = '0700000074', address = 'Str. Lalelelor 74', country = 'Romania', city = 'Ciorogarla' WHERE "ownerId" = 74;
UPDATE profiles SET "firstName" = 'Octavia', "lastName" = 'Bordei', "phoneNumber" = '0700000075', address = 'Str. Lalelelor 75', country = 'Romania', city = 'Glina' WHERE "ownerId" = 75;
UPDATE profiles SET "firstName" = 'Pavel', "lastName" = 'Voiculescu', "phoneNumber" = '0700000076', address = 'Str. Lalelelor 76', country = 'Romania', city = 'Jilava' WHERE "ownerId" = 76;
UPDATE profiles SET "firstName" = 'Ramona', "lastName" = 'Ciofu', "phoneNumber" = '0700000077', address = 'Str. Lalelelor 77', country = 'Romania', city = '1 Decembrie' WHERE "ownerId" = 77;
UPDATE profiles SET "firstName" = 'Sergiu', "lastName" = 'Grosu', "phoneNumber" = '0700000078', address = 'Str. Lalelelor 78', country = 'Romania', city = 'Snagov' WHERE "ownerId" = 78;
UPDATE profiles SET "firstName" = 'Tiberiu', "lastName" = 'Balan', "phoneNumber" = '0700000079', address = 'Str. Lalelelor 79', country = 'Romania', city = 'Peris' WHERE "ownerId" = 79;
UPDATE profiles SET "firstName" = 'Vera', "lastName" = 'Pascal', "phoneNumber" = '0700000080', address = 'Str. Lalelelor 80', country = 'Romania', city = 'Gruiu' WHERE "ownerId" = 80;
UPDATE profiles SET "firstName" = 'Adrian', "lastName" = 'Rusu', "phoneNumber" = '0700000081', address = 'Str. Lalelelor 81', country = 'Romania', city = 'Afumati' WHERE "ownerId" = 81;
UPDATE profiles SET "firstName" = 'Bogdana', "lastName" = 'Neacsu', "phoneNumber" = '0700000082', address = 'Str. Lalelelor 82', country = 'Romania', city = 'Dascalu' WHERE "ownerId" = 82;
UPDATE profiles SET "firstName" = 'Cosmin', "lastName" = 'Voicu', "phoneNumber" = '0700000083', address = 'Str. Lalelelor 83', country = 'Romania', city = 'Ganeasa' WHERE "ownerId" = 83;
UPDATE profiles SET "firstName" = 'Delia', "lastName" = 'Nastase', "phoneNumber" = '0700000084', address = 'Str. Lalelelor 84', country = 'Romania', city = 'Gruiu' WHERE "ownerId" = 84;
UPDATE profiles SET "firstName" = 'Emilia', "lastName" = 'Vasile', "phoneNumber" = '0700000085', address = 'Str. Lalelelor 85', country = 'Romania', city = 'Nuci' WHERE "ownerId" = 85;
UPDATE profiles SET "firstName" = 'Florin', "lastName" = 'Dragomir', "phoneNumber" = '0700000086', address = 'Str. Lalelelor 86', country = 'Romania', city = 'Vidra' WHERE "ownerId" = 86;
UPDATE profiles SET "firstName" = 'Geanina', "lastName" = 'Paraschiv', "phoneNumber" = '0700000087', address = 'Str. Lalelelor 87', country = 'Romania', city = 'Copaceni' WHERE "ownerId" = 87;
UPDATE profiles SET "firstName" = 'Horia', "lastName" = 'Sandu', "phoneNumber" = '0700000088', address = 'Str. Lalelelor 88', country = 'Romania', city = 'Sinesti' WHERE "ownerId" = 88;
UPDATE profiles SET "firstName" = 'Ioan', "lastName" = 'Mihai', "phoneNumber" = '0700000089', address = 'Str. Lalelelor 89', country = 'Romania', city = 'Petrachioaia' WHERE "ownerId" = 89;
UPDATE profiles SET "firstName" = 'Jana', "lastName" = 'Banu', "phoneNumber" = '0700000090', address = 'Str. Lalelelor 90', country = 'Romania', city = 'Cernica' WHERE "ownerId" = 90;
UPDATE profiles SET "firstName" = 'Katia', "lastName" = 'Stanciu', "phoneNumber" = '0700000091', address = 'Str. Lalelelor 91', country = 'Romania', city = 'Ciolpani' WHERE "ownerId" = 91;
UPDATE profiles SET "firstName" = 'Laurentiu', "lastName" = 'Dobre', "phoneNumber" = '0700000092', address = 'Str. Lalelelor 92', country = 'Romania', city = 'Dărăști-Ilfov' WHERE "ownerId" = 92;
UPDATE profiles SET "firstName" = 'Mihaela', "lastName" = 'Ene', "phoneNumber" = '0700000093', address = 'Str. Lalelelor 93', country = 'Romania', city = 'Dobroesti' WHERE "ownerId" = 93;
UPDATE profiles SET "firstName" = 'Nelu', "lastName" = 'Ivan', "phoneNumber" = '0700000094', address = 'Str. Lalelelor 94', country = 'Romania', city = 'Pantelimon' WHERE "ownerId" = 94;
UPDATE profiles SET "firstName" = 'Oana', "lastName" = 'Badea', "phoneNumber" = '0700000095', address = 'Str. Lalelelor 95', country = 'Romania', city = 'Popesti-Leordeni' WHERE "ownerId" = 95;
UPDATE profiles SET "firstName" = 'Paul', "lastName" = 'Muntean', "phoneNumber" = '0700000096', address = 'Str. Lalelelor 96', country = 'Romania', city = 'Voluntari' WHERE "ownerId" = 96;
UPDATE profiles SET "firstName" = 'Roxana', "lastName" = 'Tudose', "phoneNumber" = '0700000097', address = 'Str. Lalelelor 97', country = 'Romania', city = 'Bragadiru' WHERE "ownerId" = 97;
UPDATE profiles SET "firstName" = 'Sorin', "lastName" = 'Fratila', "phoneNumber" = '0700000098', address = 'Str. Lalelelor 98', country = 'Romania', city = 'Chiajna' WHERE "ownerId" = 98;
UPDATE profiles SET "firstName" = 'Teodora', "lastName" = 'Gheorghiu', "phoneNumber" = '0700000099', address = 'Str. Lalelelor 99', country = 'Romania', city = 'Berceni' WHERE "ownerId" = 99;
UPDATE profiles SET "firstName" = 'Vlad', "lastName" = 'Croitoru', "phoneNumber" = '0700000100', address = 'Str. Lalelelor 100', country = 'Romania', city = 'Ciorogarla' WHERE "ownerId" = 100;

DO $$
DECLARE
  user_id integer;
  num_queries integer;
  query_idx integer;
  query_type text;
  query_data text;
  query_name text;
BEGIN
  FOR user_id IN 1..100 LOOP
    num_queries := floor(random() * 11)::integer + 1;
    FOR query_idx IN 1..num_queries LOOP
      IF random() < 0.5 THEN
        query_type := 'search';
        query_data := 'example' || query_idx;
        query_name := 'Search Query ' || query_idx;
      ELSE
        query_type := 'filter';
        query_data := 'filter' || query_idx;
        query_name := 'Filter Query ' || query_idx;
      END IF;

      IF random() < 0.4 THEN
        query_name := NULL;
      END IF;

      INSERT INTO queries ("ownerId", "jsonData", name)
      VALUES (
        user_id,
        jsonb_build_object('type', query_type, 'data', query_data),
        query_name
      );
    END LOOP;
  END LOOP;
END$$;

DO $$
DECLARE
  user_count      integer := 100;
  min_friends     integer := 3;   
  max_friends     integer := 6;  
  user_id         integer;
  friend_id       integer;
  num_friends     integer;
  i               integer;
BEGIN
  CREATE TEMP TABLE temp_friends (
    id1 integer,
    id2 integer,
    CONSTRAINT unique_pair UNIQUE(id1, id2)
  ) ON COMMIT DROP;

  FOR user_id IN 1..user_count LOOP
    num_friends := floor(random() * (max_friends - min_friends + 1))::integer + min_friends;
    i := 0;
    WHILE i < num_friends LOOP
      friend_id := floor(random() * user_count)::integer + 1;
      IF friend_id <> user_id THEN
        IF user_id < friend_id THEN
          BEGIN
            INSERT INTO temp_friends (id1, id2) VALUES (user_id, friend_id);
            i := i + 1;
          EXCEPTION WHEN unique_violation THEN
            NULL;
          END;
        ELSE
          BEGIN
            INSERT INTO temp_friends (id1, id2) VALUES (friend_id, user_id);
            i := i + 1;
          EXCEPTION WHEN unique_violation THEN
            NULL;
          END;
        END IF;
      END IF;
    END LOOP;
  END LOOP;

  INSERT INTO friends (id1, id2)
    SELECT id1, id2 FROM temp_friends;
END$$;

ALTER TABLE profiles ENABLE TRIGGER ALL;
ALTER TABLE queries ENABLE TRIGGER ALL;


    